### ISSUE TITLE
onCallback functionalities 

### ISSUE THREAD

**Issue by micwise17** [seyicoded/react-native-universal-payment-gateway#4]
I would like to enquiry about the onCallback props of Gateway.payStack.
To validate the payment I need to receive the json so I am stuck in the validation process and I can't figure it out.
Can you help me with this?

**Comment by seyicoded** [comment]
Message me on WhatsApp

+2349023112671

**Comment by emmaadesile** [comment]
@seyicoded I'm also facing the same issue. The screen goes blank during the `validatePayment` process and stays that way.

**Comment by seyicoded** [comment]
resolved

**Comment by seyicoded** [comment]
@emmaadesile confirm if so
